/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomType = IDL.Variant({
  'deluxe' : IDL.Null,
  'suite' : IDL.Null,
  'standard' : IDL.Null,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'reviewText' : IDL.Text,
  'guestName' : IDL.Text,
  'rating' : IDL.Nat,
  'roomTypeStayed' : RoomType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingInquiry = IDL.Record({
  'id' : IDL.Nat,
  'submissionTimestamp' : Time,
  'specialRequests' : IDL.Text,
  'checkInDate' : Time,
  'guestName' : IDL.Text,
  'email' : IDL.Text,
  'numGuests' : IDL.Nat,
  'roomTypePreference' : RoomType,
  'checkOutDate' : Time,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRoom' : IDL.Func([Room], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookingInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTestimonialsByRating' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'getTestimonialsByRoomType' : IDL.Func(
      [RoomType],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'getTestimonialsSortedByGuestName' : IDL.Func(
      [],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'prepopulateData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingInquiry' : IDL.Func([BookingInquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomType = IDL.Variant({
    'deluxe' : IDL.Null,
    'suite' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'reviewText' : IDL.Text,
    'guestName' : IDL.Text,
    'rating' : IDL.Nat,
    'roomTypeStayed' : RoomType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingInquiry = IDL.Record({
    'id' : IDL.Nat,
    'submissionTimestamp' : Time,
    'specialRequests' : IDL.Text,
    'checkInDate' : Time,
    'guestName' : IDL.Text,
    'email' : IDL.Text,
    'numGuests' : IDL.Nat,
    'roomTypePreference' : RoomType,
    'checkOutDate' : Time,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRoom' : IDL.Func([Room], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookingInquiries' : IDL.Func(
        [],
        [IDL.Vec(BookingInquiry)],
        ['query'],
      ),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTestimonialsByRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getTestimonialsByRoomType' : IDL.Func(
        [RoomType],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getTestimonialsSortedByGuestName' : IDL.Func(
        [],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'prepopulateData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingInquiry' : IDL.Func([BookingInquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };