/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'id' : bigint,
  'submissionTimestamp' : Time,
  'specialRequests' : string,
  'checkInDate' : Time,
  'guestName' : string,
  'email' : string,
  'numGuests' : bigint,
  'roomTypePreference' : RoomType,
  'checkOutDate' : Time,
  'phone' : string,
}
export interface Room {
  'id' : bigint,
  'pricePerNight' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'amenities' : Array<string>,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export type RoomType = { 'deluxe' : null } |
  { 'suite' : null } |
  { 'standard' : null };
export interface Testimonial {
  'id' : bigint,
  'date' : Time,
  'reviewText' : string,
  'guestName' : string,
  'rating' : bigint,
  'roomTypeStayed' : RoomType,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRoom' : ActorMethod<[Room], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookingInquiries' : ActorMethod<[], Array<BookingInquiry>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAvailableRooms' : ActorMethod<[], Array<Room>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTestimonialsByRating' : ActorMethod<[bigint], Array<Testimonial>>,
  'getTestimonialsByRoomType' : ActorMethod<[RoomType], Array<Testimonial>>,
  'getTestimonialsSortedByGuestName' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'prepopulateData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingInquiry' : ActorMethod<[BookingInquiry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];