/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface BookingInquiry {
    id: bigint;
    submissionTimestamp: Time;
    specialRequests: string;
    checkInDate: Time;
    guestName: string;
    email: string;
    numGuests: bigint;
    roomTypePreference: RoomType;
    checkOutDate: Time;
    phone: string;
}
export interface Room {
    id: bigint;
    pricePerNight: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    amenities: Array<string>;
    capacity: bigint;
    roomType: RoomType;
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: bigint;
    date: Time;
    reviewText: string;
    guestName: string;
    rating: bigint;
    roomTypeStayed: RoomType;
}
export enum RoomType {
    deluxe = "deluxe",
    suite = "suite",
    standard = "standard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRoom(room: Room): Promise<void>;
    addTestimonial(testimonial: Testimonial): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllBookingInquiries(): Promise<Array<BookingInquiry>>;
    getAllRooms(): Promise<Array<Room>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAvailableRooms(): Promise<Array<Room>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTestimonialsByRating(rating: bigint): Promise<Array<Testimonial>>;
    getTestimonialsByRoomType(roomType: RoomType): Promise<Array<Testimonial>>;
    getTestimonialsSortedByGuestName(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    prepopulateData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBookingInquiry(inquiry: BookingInquiry): Promise<void>;
}
import type { BookingInquiry as _BookingInquiry, Room as _Room, RoomType as _RoomType, Testimonial as _Testimonial, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRoom(arg0: Room): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(to_candid_Room_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(to_candid_Room_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(to_candid_Testimonial_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(to_candid_Testimonial_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBookingInquiries(): Promise<Array<BookingInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingInquiries();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingInquiries();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRooms();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRooms();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsByRating(arg0: bigint): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsByRating(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsByRating(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsByRoomType(arg0: RoomType): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsByRoomType(to_candid_RoomType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsByRoomType(to_candid_RoomType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsSortedByGuestName(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsSortedByGuestName();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsSortedByGuestName();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async prepopulateData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.prepopulateData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.prepopulateData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBookingInquiry(arg0: BookingInquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingInquiry(to_candid_BookingInquiry_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingInquiry(to_candid_BookingInquiry_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BookingInquiry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingInquiry): BookingInquiry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    submissionTimestamp: _Time;
    specialRequests: string;
    checkInDate: _Time;
    guestName: string;
    email: string;
    numGuests: bigint;
    roomTypePreference: _RoomType;
    checkOutDate: _Time;
    phone: string;
}): {
    id: bigint;
    submissionTimestamp: Time;
    specialRequests: string;
    checkInDate: Time;
    guestName: string;
    email: string;
    numGuests: bigint;
    roomTypePreference: RoomType;
    checkOutDate: Time;
    phone: string;
} {
    return {
        id: value.id,
        submissionTimestamp: value.submissionTimestamp,
        specialRequests: value.specialRequests,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        email: value.email,
        numGuests: value.numGuests,
        roomTypePreference: from_candid_RoomType_n12(_uploadFile, _downloadFile, value.roomTypePreference),
        checkOutDate: value.checkOutDate,
        phone: value.phone
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pricePerNight: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    amenities: Array<string>;
    capacity: bigint;
    roomType: _RoomType;
}): {
    id: bigint;
    pricePerNight: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    amenities: Array<string>;
    capacity: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        pricePerNight: value.pricePerNight,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        amenities: value.amenities,
        capacity: value.capacity,
        roomType: from_candid_RoomType_n12(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    reviewText: string;
    guestName: string;
    rating: bigint;
    roomTypeStayed: _RoomType;
}): {
    id: bigint;
    date: Time;
    reviewText: string;
    guestName: string;
    rating: bigint;
    roomTypeStayed: RoomType;
} {
    return {
        id: value.id,
        date: value.date,
        reviewText: value.reviewText,
        guestName: value.guestName,
        rating: value.rating,
        roomTypeStayed: from_candid_RoomType_n12(_uploadFile, _downloadFile, value.roomTypeStayed)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deluxe: null;
} | {
    suite: null;
} | {
    standard: null;
}): RoomType {
    return "deluxe" in value ? RoomType.deluxe : "suite" in value ? RoomType.suite : "standard" in value ? RoomType.standard : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Room>): Array<Room> {
    return value.map((x)=>from_candid_Room_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingInquiry>): Array<BookingInquiry> {
    return value.map((x)=>from_candid_BookingInquiry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInquiry_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInquiry): _BookingInquiry {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Room_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Room): _Room {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Testimonial_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testimonial): _Testimonial {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pricePerNight: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    amenities: Array<string>;
    capacity: bigint;
    roomType: RoomType;
}): {
    id: bigint;
    pricePerNight: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    amenities: Array<string>;
    capacity: bigint;
    roomType: _RoomType;
} {
    return {
        id: value.id,
        pricePerNight: value.pricePerNight,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        amenities: value.amenities,
        capacity: value.capacity,
        roomType: to_candid_RoomType_n3(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    submissionTimestamp: Time;
    specialRequests: string;
    checkInDate: Time;
    guestName: string;
    email: string;
    numGuests: bigint;
    roomTypePreference: RoomType;
    checkOutDate: Time;
    phone: string;
}): {
    id: bigint;
    submissionTimestamp: _Time;
    specialRequests: string;
    checkInDate: _Time;
    guestName: string;
    email: string;
    numGuests: bigint;
    roomTypePreference: _RoomType;
    checkOutDate: _Time;
    phone: string;
} {
    return {
        id: value.id,
        submissionTimestamp: value.submissionTimestamp,
        specialRequests: value.specialRequests,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        email: value.email,
        numGuests: value.numGuests,
        roomTypePreference: to_candid_RoomType_n3(_uploadFile, _downloadFile, value.roomTypePreference),
        checkOutDate: value.checkOutDate,
        phone: value.phone
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: Time;
    reviewText: string;
    guestName: string;
    rating: bigint;
    roomTypeStayed: RoomType;
}): {
    id: bigint;
    date: _Time;
    reviewText: string;
    guestName: string;
    rating: bigint;
    roomTypeStayed: _RoomType;
} {
    return {
        id: value.id,
        date: value.date,
        reviewText: value.reviewText,
        guestName: value.guestName,
        rating: value.rating,
        roomTypeStayed: to_candid_RoomType_n3(_uploadFile, _downloadFile, value.roomTypeStayed)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    deluxe: null;
} | {
    suite: null;
} | {
    standard: null;
} {
    return value == RoomType.deluxe ? {
        deluxe: null
    } : value == RoomType.suite ? {
        suite: null
    } : value == RoomType.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
